### ISSUE TITLE
Component: TNM 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#399]
# Problem Space

Provide a standard representation for TNM values with OMOP.

# Proposed Solutions

Map the combination of (1) staging version, (2) value and (3) path or clin to standard 'Cancer Modifier' concepts. 

## Tasks
- [x] #402
- [x] Finalize decisions/requirements
- [x] Identify outstanding work; Create issues
- [x] Complete outstanding work 
- [x] Submit vocabulary modifications
- [x] #400
- [x] #401

**Comment by rtmill** [comment]
Documented. Will need to provide a strategy for inventory of "ready for use", but completed

**Comment by kzollove** [comment]
https://github.com/OHDSI/OncologyWG/issues/627

**Comment by kzollove** [comment]
Update documentation on TNM (use CDM v5.4 column names)
