### ISSUE TITLE
Component: Grading

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#403]
# Problem Space

Represent cancer grading in a standard format in OMOP 

# Proposed Solutions

Leverage small list of grading concepts within 'Cancer Modifier' vocabulary - leave the distinction of the meaning of that grading concept to the cancer type in which it modifiers. 

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work 
- [ ] Submit vocabulary modifications
- [ ] Document 
- [ ] Designate as 'ready for use'
