### ISSUE TITLE
Component: Date of Initial Diagnosis

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#407]
# Problem Space

Needed mechanism to identify source of truth of start date for cancer diagnosis, if known or explicitly stated in data. 

# Proposed Solutions

Use the cancer modifier "Initial diagnosis" (https://athena.ohdsi.org/search-terms/terms/734306) in the measurement table and have it reference the appropriate condition record.

## Tasks
- [x] Open up for group discussion
- [x] Finalize decisions/requirements
- [x] Identify outstanding work; Create issues
- [ ] #441
- [x] Submit vocabulary modifications: Date of Initial Diagnosis
- [x] #408
- [ ] #409
