### ISSUE TITLE
Component: Surgery 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#413]
# Problem Space

Text here

# Proposed Solutions

Text/links here

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Surgery 
- [ ] Submit vocabulary modifications: Surgery 
- [ ] Document : Surgery 
- [ ] Designate as 'ready for use': Surgery
