### ISSUE TITLE
Component: Metastasis

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#416]
# Problem Space

Standard representation for metastasis.

# Proposed Solutions

TODO ( and discussion ahead on this one)

Text/links here

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Metastasis
- [ ] Submit vocabulary modifications: Metastasis
- [ ] Document: Metastasis
- [ ] Designate as 'ready for use': Metastasis
