### ISSUE TITLE
Component: Extension/Invasion

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#420]
# Problem Space

Standard representation for Extension/Invasion

# Proposed Solutions

TODO

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Extension/Invasion
- [ ] Submit vocabulary modifications: Extension/Invasion
- [ ] Document: Extension/Invasion
- [ ] Designate as 'ready for use': Extension/Invasion
