### ISSUE TITLE
Component: Dimension

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#423]
# Problem Space

Standard representation of Dimension

# Proposed Solutions

TODO

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Dimension
- [ ] Submit vocabulary modifications: Dimension
- [ ] Document: Dimension
- [ ] Designate as 'ready for use': Dimension
