### ISSUE TITLE
Component: Chemotherapy

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#426]
# Problem Space

Standardized representation for chemotherapy

## Factors
- Regimen
- Drug Exposures 
- Dosage
- Phase/Course
- Intent
- Others?

# Proposed Solutions
TODO

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Chemotherapy
- [ ] Submit vocabulary modifications: Chemotherapy
- [ ] #427
- [ ] #428

**Comment by rtmill** [comment]
Condensing this into https://github.com/OHDSI/OncologyWG/issues/449
