### ISSUE TITLE
Component: Radiotherapy 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#429]
# Problem Space

Standard representation for radiotherapy data

# Proposed Solutions

TODO

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Radiotherapy 
- [ ] Submit vocabulary modifications: Radiotherapy 
- [ ] Document: Radiotherapy 
- [ ] Designate as 'ready for use': Radiotherapy
