### ISSUE TITLE
Component: Immunotherapy

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#432]
# Problem Space

Standard representation for Immunotherapy 

# Proposed Solutions

TODO

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Immunotherapy
- [ ] Submit vocabulary modifications: Immunotherapy
- [ ] #433
- [ ] #434

**Comment by rtmill** [comment]
Condensing this into https://github.com/OHDSI/OncologyWG/issues/449
