### ISSUE TITLE
Component: Hormone therapy

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#435]
# Problem Space

Standard representation for Hormone therapy

# Proposed Solutions

TODO

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Hormone therapy
- [ ] Submit vocabulary modifications: Hormone therapy
- [ ] #436
- [ ] #437

**Comment by rtmill** [comment]
Condensing this into #449
