### ISSUE TITLE
Component: Drug Therapy

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#449]
# Problem Space

Model representation and vocabulary for oncology related drug therapies, including:
-Chemotherapy
-Immunotherapy
-Hormone Therapy 

# Factors
- Regimen
- Vocabularies
- Relation to drug exposures
- Dosage
- Phase/Course
- Intent
- Others?

# Proposed Solutions

TODO

## Tasks
- [ ] Create proposal
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Drug Therapy
- [ ] Submit vocabulary modifications: Drug Therapy
- [ ] Document: Drug Therapy
- [ ] Designate as 'ready for use': Drug Therapy
