### ISSUE TITLE
Component: Procedure relation hierarchies

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#454]
# Problem Space

It is usually burdensome or impossible to query for procedures with specific context when creating a phenotype. Those include:
- site (site vocabulary varies by procedure vocabulary, or missing)
- type of procedure - e.g. resection, biopsy, destruction (variation of vocabularies, granularity, or missing)
- intent (not mapped and concepts can be ambiguous)

# Proposed Solutions

TODO - 
(placeholder) Create standard hierarchies of concepts that can be used relationally to identify procedures based on context. These concepts would be leveraged similarly to how "site" and "histology" are related to ICDO3 concepts, i.e. "has site", "has histology" in the concept relationship table. 

An aside, one of the difficulties that has slowed this down classifying procedures is the existence of data that contains 'high level' treatments, such as just the term "Chemotherapy", e.g. within tumor registries. This solution would have those concepts map to procedures (i.e. Chemotherapy, nos) but also have these same relational concepts (i.e. "has cancer procedure type: chemotherapy") associated with them.

Diagram from @mgurley showing a mock-up of a "Procedure type" hierarchy:
![image](https://user-images.githubusercontent.com/13469976/205173582-6f1d1d09-0374-40e3-88a4-ca95215505a4.png)

## Tasks
- [ ] Create proposal: Procedure relation hierarchies
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: Procedure relation hierarchies
- [ ] Submit vocabulary modifications: Procedure relation hierarchies
- [ ] Document: Procedure relation hierarchies
- [ ] Designate as 'ready for use': Procedure relation hierarchies
