### ISSUE TITLE
Task Group: Laterality

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#580]
# Problem Space

Text here

# Proposed Solutions

TODO

## Tasks
- [ ] Resolve Decision Points: Laterality
- [ ] Investigate & create tasks: Laterality
- [ ] Complete outstanding work: Laterality
- [ ] Validate and ingest: Laterality
- [ ] Document: Laterality
