### ISSUE TITLE
Task Group: Diagnosis Hierarchy

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#581]
# Problem Space

Text here

# Proposed Solutions

TODO

## Tasks
- [ ] Resolve Decision Points: Diagnosis Hierarchy
- [ ] Investigate & create tasks: Diagnosis Hierarchy
- [ ] Complete outstanding work: Diagnosis Hierarchy
- [ ] Validate and ingest: Diagnosis Hierarchy
- [ ] Document: Diagnosis Hierarchy

**Comment by odikia** [comment]
Thanks @rtmill ! Noted
