### ISSUE TITLE
Task Group: Specific tumor identifier

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#582]
# Problem Space

Text here

# Proposed Solutions

TODO

## Tasks
- [ ] Resolve Decision Points: Specific tumor identifier
- [ ] Investigate & create tasks: Specific tumor identifier
- [ ] Complete outstanding work: Specific tumor identifier
- [ ] Validate and ingest: Specific tumor identifier
- [ ] Document: Specific tumor identifier
