### ISSUE TITLE
Task Group: Cancer Biomarkers

### ISSUE THREAD

**Issue by tfalcs** [OHDSI/OncologyWG#644]
# Problem Space

SNOMED is increasingly accounting for important cancer diagnostic information, which will eventually be present in Athena. These concepts will overlap with their corresponding Cancer Modifier concepts. Since SNOMED is well maintained and is synonymous with OMOP and querying for standard concepts, SNOMED should be the standard for these overlapping concepts. 

# Proposed Solutions

De-standardize Cancer Modifier concepts that have an equivalent SNOMED concept  

## Tasks
- [ ] Resolve Decision Points: X
- [X ] Investigate & create tasks: X
- [ ] Complete outstanding work: X
- [ ] Validate and ingest: X
- [ ] Document: X
