### ISSUE TITLE
Task Group: X 

### ISSUE THREAD

**Issue by tfalcs** [OHDSI/OncologyWG#645]
# Problem Space

Text here

# Proposed Solutions

TODO

## Tasks
- [ ] Resolve Decision Points: X
- [ ] Investigate & create tasks: X
- [ ] Complete outstanding work: X
- [ ] Validate and ingest: X
- [ ] Document: 
- [ ] #644
