### ISSUE TITLE
Task Group: Cancer Biomarkers

### ISSUE THREAD

**Issue by tfalcs** [OHDSI/OncologyWG#646]
# Problem Space

CAP protocols are used and their forms are completed for the diagnoses of cancers. These data should be in the OMOP CDM for use in cancer observational research. A first step is to ensure the information asked about in these CAP protocols and their corresponding answers have standard concepts in a relevant vocabulary with the OMOP CDM. 

# Proposed Solutions

Ensure each CAP data element has a standard concept in the OMOP CDM and is represented by only one standard concept

## Tasks
- [ ] Resolve Decision Points: X
- [ ] Investigate & create tasks: X
- [ ] Complete outstanding work: X
- [ ] Validate and ingest: X
- [ ] Document: X
- [ ] #644
