### ISSUE TITLE
Task Group: Cancer biomarkers

### ISSUE THREAD

**Issue by tfalcs** [OHDSI/OncologyWG#647]
# Problem Space

Currently the OMOP Genomic vocabulary is the vocabulary used to map sequencing (NGS) data into OMOP. However, the current representation of the concepts is not question/answer (question in concept_id field; answer a separate column (_value field) of same table) and the current concept_names of many of the concepts indicate simply measurement of, making it ambiguous as to what the finding is. 

# Proposed Solutions

Decision point: to represent NGS data as question/answer (as described above) or to update the concept_name to indicate an implicit finding. 

## Tasks
- [ ] Resolve Decision Points: X
- [ ] Investigate & create tasks: X
- [ ] Complete outstanding work: X
- [ ] Validate and ingest: X
- [ ] Document: X
- [ ] #644
